logging:
  level:
    com:
      mycompany:
        myapp: INFO
spring:
  application:
    name: AIsample
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/AIsample
    username: AIsample
